---
# tasks file for setup-ws
#
#
- name: "Install python3"
  dnf:
    name: "python3"
    state: present

- name: "Gather Facts"
  setup:

- name: "Installing Apache Webserver"    
  dnf:
    name: "httpd"
    state: present
- name: "Installing php software"
  dnf:
    name: "php"
    state: present
- name: "Copy webpage"
  copy:
    dest: "/var/www/html/index.php"
    content: |
          <pre> 
          <?php 
             print `/usr/sbin/ifconfig`;
          ?>
          <pre>
- name: "start http server"
  service:
    name: "httpd"
    state: started
    enabled: true

- name: "install firewall pakckage"
  dnf:
    name: "firewalld"
    state: present

- name: "start firwalld"
  service:
    name: "firewalld"
    state: started
    enabled: true

- name: "Firewall Allow http service"
  firewalld:
    service: "http"
    immediate: yes
    state: enabled
    permanent: yes
